### PR TITLE
Fix loadAndRun onLoad and continued streaming

### LINKED ISSUE #44: loadAndRun on an empty topic terminates without callback or continued streaming
**Describe the bug**

`loadAndRun` on an empty topic does not fire the `onLoad` callback, nor does it continue to stream records post-load. Additionally when subscribing to multiple topics, if one is empty `loadAndRun` will not continue to stream it post load.

**To Reproduce**

use loadAndRun on an empty topic, or on two topics where one is empty

**Expected behavior**

loadAndRun should fire the `onLoad` and continue streaming regardless of the topic's contents

**Additional context**

### PR DESCRIPTION
**Pull request by bcarter97**
## Description

Fixes a bug where loadAndRun semantics fail for empty topics. Also copied over the relevant documentation from https://github.com/sky-uk/kafka-topic-loader/blob/master/src/main/scala/uk/sky/kafka/topicloader/TopicLoader.scala#L70

## Related Issues

- Fixes #44

## Definition of Done:

The Below tasks should be completed before marking a PR as ready for review.

- [x] Added / Removed / Updated relevant tests
- [x] Scaladoc updated

### CODE REVIEW

File: src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala [hunk 1]
```diff
@@ -96,32 +107,41 @@ trait TopicLoader {
...
-      logOffsets                   = beginningOffsetPerPartition.map { case (partition, offset) =>
+      logOffsets                   = beginningOffsetPerPartition.map { (partition, offset) =>
                                        partition -> LogOffsets(offset, endOffsets(partition))
                                      }
       _                           <- consumer.unsubscribe
-    } yield {
-      val offsets = logOffsets.filter { case (_, o) => o.highest > o.lowest }
-      NonEmptyMap.fromMap(SortedMap.from(offsets))
-    }
+    } yield NonEmptyMap.fromMap(SortedMap.from(logOffsets))
```
Comment (bcarter97) [inline src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala:126]: If we do the non-empty offset filtering here, then our consumer never subscribes to the empty partitions in loadAndRun.

File: src/test/scala/utils/EmbeddedKafka.scala [hunk 2]
```diff
@@ -17,7 +17,7 @@ trait EmbeddedKafka[F[_]] {
   } yield EmbeddedKafkaConfig(kafkaPort, zooKeeperPort, customBrokerProperties = Map("log.roll.ms" -> "10"))
 
   def embeddedKafkaR(kafkaConfig: EmbeddedKafkaConfig)(using F: Async[F]): Resource[F, KafkaServer] =
-    Resource.make(F.delay(Underlying.start()(kafkaConfig).broker))(server => F.delay(server.shutdown()).void)
+    Resource.make(F.blocking(Underlying.start()(kafkaConfig).broker))(server => F.blocking(server.shutdown()).void)
```
Comment (bcarter97) [inline src/test/scala/utils/EmbeddedKafka.scala:20]: Embedded Kafka uses the file system so it's blocking

File: src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala [hunk 3]
```diff
@@ -34,56 +34,67 @@ trait TopicLoader {
...
+        _          <- OptionT.liftF(logOffsets.toNel.traverse((tp, o) => consumer.seek(tp, o.lowest)))
+      } yield consumer.records.map(_.record).through(filterBelowHighestOffset(logOffsets))
+    }.getOrElse(Stream.empty))
+    .flatten
 
   private def filterBelowHighestOffset[F[_] : Monad : LoggerFactory, K, V](
       logOffsets: NonEmptyMap[TopicPartition, LogOffsets]
   ): Pipe[F, ConsumerRecord[K, V], ConsumerRecord[K, V]] = {
+    val nonEmptyOffsets =
+      logOffsets.toSortedMap.filter((_, o) => o.highest > 0)
```
Comment (bcarter97) [inline src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala:94]: This is the meat of the fix, previously we were filtering off non-empty offsets before this point. This is important as it meant we were not subscribing to empty partitions. for loadAndRun we want to subscribe to all partitions, but only `load` from those that are non-empty.

File: src/test/scala/integration/TopicLoaderIntSpec.scala [hunk 4]
```diff
@@ -212,6 +212,59 @@ class TopicLoaderIntSpec extends KafkaSpecBase[IO] {
...
+      for {
+        loadState  <- Ref.of[IO, Boolean](false)
+        topicState <- Ref.empty[IO, Seq[(String, String)]]
+        _          <- createCustomTopics(topics)
+        _          <- publishStringMessages(testTopic1, forTopic1)
+        assertion  <- loadAndRunR(topics)(
+                        _ => loadState.set(true),
+                        r => topicState.getAndUpdate(_ :+ r).void
+                      ).surround {
+                        for {
```
Comment (lacarvalho91) [inline src/test/scala/integration/TopicLoaderIntSpec.scala:255]: shall we extract this into a val, gets a bit messy with the nested for comps

File: src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala [hunk 5]
```diff
@@ -34,56 +34,67 @@ trait TopicLoader {
...
   private def load[F[_] : Async : LoggerFactory, K, V](
-      consumer: KafkaConsumer[F, K, V],
-      logOffsets: NonEmptyMap[TopicPartition, LogOffsets]
-  ): Stream[F, ConsumerRecord[K, V]] = consumer.records.map(_.record).through(filterBelowHighestOffset(logOffsets))
+      topics: NonEmptyList[String],
+      strategy: LoadTopicStrategy,
+      consumer: KafkaConsumer[F, K, V]
+  ): Stream[F, ConsumerRecord[K, V]] = Stream
+    .eval({
+      for {
```
Comment (lacarvalho91) [inline src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala:82]: why has all this moved from `loadAndRun` to here? i can read the code of course but i just don't really understand the changes

Comment (bcarter97) [reply src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala:82]: Both load and loadAndRun were doing the same thing, but loadAndRun was hooking onto the finalize and appending a new stream. Thought it made sense to pull out the load stream so both load and loadAndRun can use it

File: src/test/scala/integration/TopicLoaderIntSpec.scala (hunk 4 above)
Comment (bcarter97) [reply src/test/scala/integration/TopicLoaderIntSpec.scala]: https://github.com/sky-uk/fs2-kafka-topic-loader/pull/45/commits/b6093cd32465deabf02fe36be4c524ab2ffcf6cf

File: src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala (hunk 5 above)
Comment (lacarvalho91) [reply src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala:82]: what you say makes sense, its just surprising me that they do the same thing but the previous impl of `load` was so simple

File: src/test/scala/integration/TopicLoaderIntSpec.scala [hunk 6]
```diff
@@ -190,25 +190,87 @@ class TopicLoaderIntSpec extends KafkaSpecBase[IO] {
...
+        assertion  <- testState(loadState, topicState)
+      } yield assertion
+    }
+
+    "execute callback if the topic is empty and keep streaming" in withKafkaContext { ctx =>
+      import ctx.given
+
+      val postLoad = records(1 to 15)
+
+      def testState(loadState: Ref[IO, Boolean], topicState: Ref[IO, Seq[(String, String)]]): IO[Assertion] =
```
Comment (lacarvalho91) [inline src/test/scala/integration/TopicLoaderIntSpec.scala:223]: maybe `assertPostLoadRecordsConsumed` if i'm understanding it right

also, can we extract and reuse in the next test? or are they too different

File: src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala (hunk 5 above)
Comment (bcarter97) [reply src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala:82]: I think the previous impl was slightly wrong, and more has to be done in the `load` method now (like assign all partitions and seek to beginning)

File: src/test/scala/integration/TopicLoaderIntSpec.scala (hunk 6 above)
Comment (bcarter97) [reply src/test/scala/integration/TopicLoaderIntSpec.scala]: https://github.com/sky-uk/fs2-kafka-topic-loader/pull/45/commits/78e1175c36a6e9d3fa187ddadb05501139137db5

**Review by lacarvalho91 — APPROVED** [review]
