### PR TITLE
Complete stream if lowest offset is not 0

### LINKED ISSUE #52: Topics with a delete policy hang after deletion
**Describe the bug**

If the topic `cleanup.policy` is set to delete, and messages have been deleted on a topic, the next time TopicLoader runs it will hang indefinitely.

When the earliest non-empty offset is not 0, i.e. when messages have been deleted, we should check if highest offset > lowest offset, rather than highest offset > 0.

**To Reproduce**

Trigger deletion of Kafka messages and attempt to use TopicLoader on this topic.

**Expected behavior**

Topic Loader should terminate on a topic that has had messages deleted - more explicitly when the lowest offset is not 0.

**Additional context**

By delete i mean **not** when tombstoned, but actually deleted via the `delete` cleanup policy.

### PR DESCRIPTION
**Pull request by bcarter97**
## Description

Fixes a bug where the lowest offset not being 0 caused the stream to not terminate.

## Related Issues

- Fixes #52

## Definition of Done:

The Below tasks should be completed before marking a PR as ready for review.

- [x] Added / Removed / Updated relevant tests
- [ ] Scaladoc updated

### CODE REVIEW

File: src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala [hunk 1]
```diff
@@ -77,21 +79,27 @@ trait TopicLoader {
...
-    .flatten
+    }.getOrElse(Stream.empty)
+  }.flatten
 
   private def filterBelowHighestOffset[F[_] : Monad : LoggerFactory, K, V](
       logOffsets: NonEmptyMap[TopicPartition, LogOffsets]
   ): Pipe[F, ConsumerRecord[K, V], ConsumerRecord[K, V]] = {
     val nonEmptyOffsets =
-      logOffsets.toSortedMap.filter((_, o) => o.highest > 0)
+      logOffsets.toSortedMap.filter((_, o) => o.highest > o.lowest)
```
Comment (bcarter97) [inline src/main/scala/uk/sky/fs2/kafka/topicloader/TopicLoader.scala:102]: This was incorrect, as the lowest offset when the topic policy is set to delete may not be 0.

**Review by lacarvalho91 — APPROVED** [review]
